development:
  domain_url: http://shop.storefront.com
  secure_domain_url: https://shop.storefront.com
  sub_domain: shop
  separate_url: shop.storefront
production:
  domain_url: http://saasspree.railsfactory.com
  secure_domain_url: https://saasspree.railsfactory.com
  sub_domain: saasspree
  separate_url: saasspree.railsfactory
